---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: always
  image: pelotech/drone-helm3
  settings:
    helm_command: lint
    chart: ./

- name: discord
  pull: always
  image: appleboy/drone-discord:1.0.0
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    status:
    - changed
    - failure

---
kind: pipeline
name: release-version

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag

steps:
  - name: generate-chart
    pull: default
    image: alpine/helm:3.3.0
    commands:
      - apk add --no-cache curl
      - helm dependency update
      - helm package ./
      - mkdir gitea
      - mv gitea*.tgz gitea/
      - curl -o gitea/index.yaml https://dl.gitea.io/charts/index.yaml
      - helm repo index gitea/ --url https://dl.gitea.io/charts --merge gitea/index.yaml
  - name: upload-chart
    pull: default
    image: plugins/s3:latest
    settings:
      bucket: releases
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: gitea/*
      target: /charts
      strip_prefix: gitea/