---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: always
  image: pelotech/drone-helm3
  settings:
    helm_command: lint
    chart: ./
  when:
    event:
    - pull_request

- name: discord
  pull: always
  image: appleboy/drone-discord:1.0.0
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    event:
    - push
    - tag
    - pull_request
    status:
    - changed
    - failure
