---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: arm64

steps:
  - name: yaml lint
    pull: always
    image: cytopia/yamllint:alpine-1
    commands:
      - yamllint -f colored .
