suite: gitea database configuration
release:
  name: gitea-unittests
  namespace: testing
templates:
- templates/gitea/configmap.yaml
tests:
- it: database configuration using TPL
  set:
    gitea.config.database:
      host: "db-host"
      port: "3306"
      user: "db-user"
      password: "{{ .Values.global.dbPassword }}"
    global.dbPassword: "secure-password"
  asserts:
  - isKind:
      of: ConfigMap
  - contains:
      path: data.app.ini
      content: |
        [database]
        host=db-host
        port=3306
        user=db-user
        password=secure-password
