apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea.fullname" . }}-restore-config
  namespace: {{ .Release.Namespace }}
data:
  restoreData: {{ .Values.backup.restore.toRestore | quote }}
  restorePsql: {{ .Values.backup.restore.toRestore | quote }}
