suite: deployment template (securityContexts)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/deployment.yaml
  - templates/gitea/config.yaml
tests:
  - it: default values
    template: templates/gitea/deployment.yaml
    asserts:
      - isNullOrEmpty:
          path: spec.template.spec.initContainers[0].securityContext
      - isNullOrEmpty:
          path: spec.template.spec.initContainers[1].securityContext
      - equal:
          path: spec.template.spec.initContainers[2].securityContext.runAsUser
          value: 1000
      - isNullOrEmpty:
          path: spec.template.spec.containers[0].securityContext
  
  - it: initContainers have securityContext (runAsUser)
    set:
      initContainerSecurityContext:
        runAsUser: 1001
      signing.enabled: true
    template: templates/gitea/deployment.yaml
    asserts:
      - equal:
          path: spec.template.spec.initContainers[0].securityContext.runAsUser
          value: 1001
      - equal:
          path: spec.template.spec.initContainers[1].securityContext.runAsUser
          value: 1001
      - equal:
          path: spec.template.spec.initContainers[2].securityContext.runAsUser
          value: 1001
      - equal:
          path: spec.template.spec.initContainers[3].securityContext.runAsUser
          value: 1001
      - isNullOrEmpty:
          path: spec.template.spec.containers[0].securityContext

  - it: initContainers inherit securityContext (runAsUser)
    template: templates/gitea/deployment.yaml
    set:
      containerSecurityContext:
        runAsUser: 1002
      signing.enabled: true
    asserts:
      - equal:
          path: spec.template.spec.initContainers[0].securityContext.runAsUser
          value: 1002
      - equal:
          path: spec.template.spec.initContainers[1].securityContext.runAsUser
          value: 1002
      - equal:
          path: spec.template.spec.initContainers[2].securityContext.runAsUser
          value: 1002
      - equal:
          path: spec.template.spec.initContainers[3].securityContext.runAsUser
          value: 1002
      - equal:
          path: spec.template.spec.containers[0].securityContext.runAsUser
          value: 1002

  - it: initContainers have different securityContext (runAsUser) than containers
    template: templates/gitea/deployment.yaml
    set:
      containerSecurityContext:
        runAsUser: 1003
      initContainerSecurityContext:
        runAsUser: 1004
      signing.enabled: true
    asserts:
      - equal:
          path: spec.template.spec.initContainers[0].securityContext.runAsUser
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[1].securityContext.runAsUser
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[2].securityContext.runAsUser
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[3].securityContext.runAsUser
          value: 1004
      - equal:
          path: spec.template.spec.containers[0].securityContext.runAsUser
          value: 1003

  - it: initContainers have different securityContext (runAsGroup) than containers
    template: templates/gitea/deployment.yaml
    set:
      containerSecurityContext:
        runAsGroup: 1003
      initContainerSecurityContext:
        runAsGroup: 1004
      signing.enabled: true
    asserts:
      - equal:
          path: spec.template.spec.initContainers[0].securityContext.runAsGroup
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[1].securityContext.runAsGroup
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[2].securityContext.runAsGroup
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[3].securityContext.runAsGroup
          value: 1004
      - equal:
          path: spec.template.spec.initContainers[2].securityContext.runAsUser
          value: 1000
      - equal:
          path: spec.template.spec.initContainers[3].securityContext.runAsUser
          value: 1000
      - equal:
          path: spec.template.spec.containers[0].securityContext.runAsGroup
          value: 1003
