suite: gitea inline configuration template
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/configmap.yaml
tests:
  - it: Inline configuration with TPL function
    set:
      gitea:
        config:
          APP_NAME: "{{ .Release.Name }}-gitea"
          server:
            DOMAIN: "{{ .Values.global.giteaDomain }}"
    global:
      giteaDomain: "gitea.example.com"
    asserts:
      - isKind:
          of: ConfigMap
      - contains:
          path: data.app.ini
          content: |
            APP_NAME=gitea-unittests-gitea
            [server]
            DOMAIN=gitea.example.com
  - it: General section without TPL
    set:
      gitea:
        config:
          APP_NAME: "StaticAppName"
          RUN_USER: "git"
          server:
            ROOT_URL: "https://static.example.com"
    asserts:
      - isKind:
          of: ConfigMap
      - contains:
          path: data.app.ini
          content: |
            APP_NAME=StaticAppName
            RUN_USER=git
            [server]
            ROOT_URL=https://static.example.com
  - it: Fail on invalid top-level key
    set:
      gitea:
        config:
          INVALID_KEY: "ShouldFail"
    asserts:
      - failsWith:
          message: "Key INVALID_KEY cannot be on top level of configuration"