suite: deployment mounts inline-config existing secret
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/deployment.yaml
  - templates/gitea/config.yaml  
tests:
  - it: mounts specified existing secret 
    template: templates/gitea/deployment.yaml
    set:
      gitea:
        inlineConfigExistingSecret: "inline-config-secret"
    asserts:
      - contains:
          path: spec.template.spec.volumes
          content:
            name: inline-config-sources
            secret:
              secretName: inline-config-secret
  - it: mounts default templated secret when not specified 
    template: templates/gitea/deployment.yaml
    set:
      gitea:
        inlineConfigExistingSecret: ""
    asserts:
      - contains:
          path: spec.template.spec.volumes
          content:
            name: inline-config-sources
            secret:
              secretName: gitea-unittests-inline-config
