suite: deployment template (basic)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/deployment.yaml
  - templates/gitea/config.yaml
tests:
  - it: renders a deployment
    template: templates/gitea/deployment.yaml
    asserts:
      - hasDocuments:
          count: 1
      - containsDocument:
          kind: Deployment
          apiVersion: apps/v1
          name: gitea-unittests
  - it: deployment labels are set
    template: templates/gitea/deployment.yaml
    set:
      deployment.labels:
        hello: world
    asserts:
      - isSubset:
          path: metadata.labels
          content:
            hello: world
      - isSubset:
          path: spec.template.metadata.labels
          content:
            hello: world
  - it: "injects TMP_EXISTING_ENVS_FILE as environment variable to 'init-app-ini' init container"
    template: templates/gitea/deployment.yaml
    asserts:
      - contains:
          path: spec.template.spec.initContainers[1].env
          content:
            name: TMP_EXISTING_ENVS_FILE
            value: /tmp/existing-envs
  - it: "injects ENV_TO_INI_MOUNT_POINT as environment variable to 'init-app-ini' init container"
    template: templates/gitea/deployment.yaml
    asserts:
      - contains:
          path: spec.template.spec.initContainers[1].env
          content:
            name: ENV_TO_INI_MOUNT_POINT
            value: /env-to-ini-mounts
