suite: Test gitea.inline_configuration
templates:
  - templates/_helpers.tpl

tests:
  - it: should render inline configuration with correct APP_NAME
    set:
      gitea.config.APP_NAME: "TestApp"
    asserts:
      - equal:
          path: data.gitea.config.APP_NAME
          value: "TestApp"

  - it: should render inline configuration with correct RUN_USER
    set:
      gitea.config.RUN_USER: "testuser"
    asserts:
      - equal:
          path: data.gitea.config.RUN_USER
          value: "testuser"

  - it: should render inline configuration with default values
    set:
      gitea.config.APP_NAME: "TestApp"
      gitea.config.RUN_USER: "testuser"
      gitea.config.RUN_MODE: "dev"
      gitea.config.repository.ROOT: "~/test-repositories"
      gitea.config.repository.pull-request.WORK_IN_PROGRESS_PREFIXES: "WIP:,[WIP]:"
    asserts:
      - hasKey:
          path: data.gitea.config.repository
      - equal:
          path: data.gitea.config.APP_NAME
          value: "TestApp"
      - equal:
          path: data.gitea.config.RUN_USER
          value: "testuser"
      - equal:
          path: data.gitea.config.RUN_MODE
          value: "dev"