suite: gitea inline configuration
release:
  name: gitea-unittests
  namespace: testing
templates:
- gitea/templates/_helpers.tpl
tests:
- it: should render inline configuration with TPL
  set:
    gitea:
      config:
        server:
          PROTOCOL: "https"
        database:
          HOST: "localhost"
  asserts:
  - contains:
      path: gitea.inline_configuration
      value: "server:\n  PROTOCOL=https"
  - contains:
      path: gitea.inline_configuration
      value: "database:\n  HOST=localhost"
- it: handles general settings with TPL
  set:
    gitea:
      config:
        APP_NAME: "Gitea Test"
        RUN_USER: "gitea"
        RUN_MODE: "prod"
  asserts:
  - contains:
      path: gitea.inline_configuration
      value: "_generals_:

        \  - APP_NAME=Gitea Test

        \  - RUN_USER=gitea

        \  - RUN_MODE=prod"
