suite: config template | metrics section (metrics token)
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: metrics token is set
    template: templates/gitea/config.yaml
    set:
      gitea:
        metrics:
          enabled: true
          token: "somepassword"
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.metrics
          value: |-
            ENABLED=true
            TOKEN=somepassword
