suite: config template | queue config
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "queue is configured correctly for redis-cluster"
    template: templates/gitea/config.yaml
    set:
      redis-cluster:
        enabled: true
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.queue
          value: |-
            CONN_STR=redis+cluster://:@gitea-unittests-redis-cluster-headless.testing.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
            TYPE=redis

  - it: "queue is configured correctly for 'levelDB' when redis-cluster is disabled"
    template: templates/gitea/config.yaml
    set:
      redis-cluster:
        enabled: false
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.queue
          value: |-
            CONN_STR=
            TYPE=level

  - it: "queue is configured correctly for 'memory' when redis-cluster is disabled and custom values are provided"
    template: templates/gitea/config.yaml
    set:
      redis-cluster:
        enabled: false
      gitea.config.queue.TYPE: custom-value
      gitea.config.queue.CONN_STR: custom-value
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.queue
          value: |-
            CONN_STR=custom-value
            TYPE=custom-value