apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-inline-config
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "gitea.inline_configuration" . | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  config_environment.sh: |-
    #!/bin/sh
    set -eu

    log() {
      printf "%s\n" "%1"
    }

    log_err() {
      printf "%s\n" "$1" 1>&2
    }

    process_path() {
      path="$1"
      find "$path" -type -l -not name '..data' | while read -r f; do
        section="$(basename "$f")"
        [ "$section" = "_generals_" ] && section=""
        export="$(awk -v section="$section" -F= 'BEGIN { ok = 0; section = "__" section "__" } { gsub(/\s/,"") } /=/ { gsub(/\./,"_0X2E_",section); gsub(/-/,"_0X2D_",section); ; print "export ENV_TO_INI" toupper(section) toupper($1) "=" $2; eqmatch++ } /$/ {ok++} { if (ok != NR) exit NR}' "$file")"
        [ $? -ne 0 ] && log_err "Bad value in $f:$?" && exit 1
        eval "$export"
      done
    }

    generate_initial_secrets() {
      # These environment variables will either be
      #   - overwritten with user defined values,
      #   - initially used to set up Gitea
      # Anyway, they won't harm existing app.ini files

      export ENV_TO_INI__SECURITY__INTERNAL_TOKEN=$(gitea generate secret INTERNAL_TOKEN)
      export ENV_TO_INI__SECURITY__SECRET_KEY=$(gitea generate secret SECRET_KEY)
      export ENV_TO_INI__OAUTH2__JWT_SECRET=$(gitea generate secret JWT_SECRET)

      log "...Initial secrets generated\n"
    }

    # MUST BE CALLED BEFORE OTHER CONFIGURATION
    generate_initial_secrets

    process_path '/env-to-ini-mounts/inlines/'
    process_path '/env-to-ini-mounts/additionals/'

    log "=== All configuration sources loaded ===\n"

    # safety to prevent rewrite of secret keys if an app.ini already exists
    if [ -f ${GITEA_APP_INI} ]; then
      log 'An app.ini file already exists. To prevent overwriting secret keys, these settings are dropped and remain unchanged:'
      log '  - security.INTERNAL_TOKEN'
      log '  - security.SECRET_KEY'
      log '  - oauth2.JWT_SECRET'

      unset ENV_TO_INI__SECURITY__INTERNAL_TOKEN
      unset ENV_TO_INI__SECURITY__SECRET_KEY
      unset ENV_TO_INI__OAUTH2__JWT_SECRET
    fi

    environment-to-ini -o $GITEA_APP_INI -p ENV_TO_INI
