{{- if and .Values.signing.enabled (not (empty .Values.signing.privateKey)) (empty .Values.signing.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.gpg-key-secret-name" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.signing.privateKey | b64enc }}
{{- end }}
