{{- if and (.Values.gitea.metrics.serviceMonitor.enabled) (.Values.gitea.config.metrics) (.Values.gitea.config.metrics.TOKEN) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.metrics-secret-name" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.gitea.config.metrics.TOKEN  | b64enc }}
{{- end }}
