{{- if and .Values.persistence.enabled .Values.persistence.create }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.claimName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
{{ .Values.persistence.annotations | toYaml | indent 4}}
  labels:
{{ .Values.persistence.labels | toYaml | indent 4}}
spec:
  accessModes:
  {{- if gt .Values.replicaCount 1.0 }}
      - ReadWriteMany
  {{- else }}
    {{- .Values.persistence.accessModes | toYaml | nindent 4 }}
  {{- end }}
  volumeMode: Filesystem
  {{- include "gitea.persistence.storageClass" . | nindent 2 }}
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if and .Values.backup.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.backup.pvc.claimName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
{{ .Values.backup.annotations | toYaml | indent 4}}
  labels:
{{ .Values.backup.pvc.labels | toYaml | indent 4}}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  {{- include "gitea.backup.storageClass" . | nindent 2 }}
  {{- with .Values.backup.pvc.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.pvc.size }}
{{- end }}