suite: actions template | config-scripts
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/actions/config-scripts.yaml
tests:
  - it: renders a deployment
    template: templates/gitea/actions/config-scripts.yaml
    set:
      actions:
        job:
          enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - containsDocument:
          kind: ConfigMap
          apiVersion: v1
          name: gitea-unittests-scripts
