suite: actions template | config-act-runner
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/gitea/actions/config-act-runner.yaml
tests:
  - it: renders a deployment
    template: templates/gitea/actions/config-act-runner.yaml
    set:
      actions:
        statefulset:
          enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - containsDocument:
          kind: ConfigMap
          apiVersion: v1
          name: gitea-unittests-act-runner-config
