name: Build and Release Helm Chart
on:
  push:
    branches:
      - main  # Adjust to your release branch
  pull_request:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Build Helm dependencies
        run: |
          helm dependency build .
      - name: Package Helm chart
        run: |
          helm package . --destination dist
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          # body_path: CHANGELOG.md
          tag_name: ${{ steps.short-sha.outputs.sha }}
          fail_on_unmatched_files: true
          files: dist/*
          # generate_release_notes: true